from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 1222)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 210, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(60, 90, 361, 141))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 210, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        # self.label_3.setGeometry(QtCore.QRect(60, 60, 48, 20))
        self.label_3.setGeometry(QtCore.QRect(60, 60, 48, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 240, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 650, 61, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 1020, 61, 20))
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 250, 75, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(600, 60, 61, 20))
        self.label_7.setObjectName("label_7")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        # self.layoutWidget.setGeometry(QtCore.QRect(60, 20, 801, 31))
        self.layoutWidget.setGeometry(QtCore.QRect(60, 20, 801, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        # self.layoutWidget1.setGeometry(QtCore.QRect(600, 110, 219, 74))
        self.layoutWidget1.setGeometry(QtCore.QRect(600, 110, 219, 74))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 2, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        # self.tabWidget.setGeometry(QtCore.QRect(60, 270, 811, 371))
        self.tabWidget.setGeometry(QtCore.QRect(60, 270, 811, 371))
        # self.tabWidget.setIconSize(QtCore.QSize(40, 20))
        self.tabWidget.setIconSize(QtCore.QSize(40, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.tableView = QtWidgets.QTableView(self.tabWidgetPage1)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 811, 351))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.tableView_3 = QtWidgets.QTableView(self.tabWidgetPage2)
        self.tableView_3.setGeometry(QtCore.QRect(0, 0, 811, 351))
        self.tableView_3.setObjectName("tableView_3")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.tableView_4 = QtWidgets.QTableView(self.tabWidgetPage3)
        self.tableView_4.setGeometry(QtCore.QRect(0, 0, 811, 351))
        self.tableView_4.setObjectName("tableView_4")
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(60, 680, 811, 321))
        # self.tabWidget_2.setIconSize(QtCore.QSize(40, 20))
        self.tabWidget_2.setIconSize(QtCore.QSize(40, 20))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidgetPage1_2 = QtWidgets.QWidget()
        self.tabWidgetPage1_2.setObjectName("tabWidgetPage1_2")
        self.tableView_2 = QtWidgets.QTableView(self.tabWidgetPage1_2)
        self.tableView_2.setGeometry(QtCore.QRect(0, 0, 811, 301))
        self.tableView_2.setObjectName("tableView_2")
        self.tabWidget_2.addTab(self.tabWidgetPage1_2, "")
        self.tabWidgetPage2_2 = QtWidgets.QWidget()
        self.tabWidgetPage2_2.setObjectName("tabWidgetPage2_2")
        self.tableView_5 = QtWidgets.QTableView(self.tabWidgetPage2_2)
        self.tableView_5.setGeometry(QtCore.QRect(0, 0, 811, 301))
        self.tableView_5.setObjectName("tableView_5")
        self.tabWidget_2.addTab(self.tabWidgetPage2_2, "")
        self.tabWidgetPage3_2 = QtWidgets.QWidget()
        self.tabWidgetPage3_2.setObjectName("tabWidgetPage3_2")
        self.tableView_6 = QtWidgets.QTableView(self.tabWidgetPage3_2)
        self.tableView_6.setGeometry(QtCore.QRect(0, 0, 811, 301))
        self.tableView_6.setObjectName("tableView_6")
        self.tabWidget_2.addTab(self.tabWidgetPage3_2, "")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(461, 90, 71, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(3)
        self.spinBox.setObjectName("spinBox")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(430, 60, 71, 20))
        self.label_18.setObjectName("label_18")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 1050, 460, 74))
        # self.widget.setGeometry(QtCore.QRect(60, 1050, 460, 7))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 3, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 1, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 2, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "压力工具"))
        self.pushButton_2.setText(_translate("MainWindow", "计算"))
        self.pushButton_3.setText(_translate("MainWindow", "选择"))
        self.label_3.setText(_translate("MainWindow", "表单："))
        self.label_4.setText(_translate("MainWindow", "输入数据：："))
        self.label_5.setText(_translate("MainWindow", "输出数据：："))
        self.label_6.setText(_translate("MainWindow", "计算结果："))
        self.pushButton_4.setText(_translate("MainWindow", "保存数据"))
        self.label_7.setText(_translate("MainWindow", "参数设置："))
        self.pushButton.setText(_translate("MainWindow", "打开文件"))
        self.label_8.setText(_translate("MainWindow", "重力加速度g："))
        self.lineEdit_4.setText(_translate("MainWindow", "9.8"))
        self.label_9.setText(_translate("MainWindow", "Eaton系数a："))
        self.lineEdit_5.setText(_translate("MainWindow", "1"))
        self.label_10.setText(_translate("MainWindow", "Eaton指数n："))
        self.lineEdit_6.setText(_translate("MainWindow", "9"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "输入1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "输入2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("MainWindow", "输入3"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage1_2), _translate("MainWindow", "输出1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage2_2), _translate("MainWindow", "输出2"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage3_2), _translate("MainWindow", "输出3"))
        self.label_18.setText(_translate("MainWindow", "打开文件数："))
        self.label_15.setText(_translate("MainWindow", "文件1输出："))
        self.label.setText(_translate("MainWindow", "Σ△TTI:"))
        self.label_2.setText(_translate("MainWindow", "Σ△TTPI:"))
        self.label_16.setText(_translate("MainWindow", "文件2输出："))
        self.label_11.setText(_translate("MainWindow", "Σ△TTI:"))
        self.label_12.setText(_translate("MainWindow", "Σ△TTPI:"))
        self.label_17.setText(_translate("MainWindow", "文件3输出："))
        self.label_13.setText(_translate("MainWindow", "Σ△TTI:"))
        self.label_14.setText(_translate("MainWindow", "Σ△TTPI:"))
